# Generated by Django 3.1 on 2023-08-11 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20230811_0239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
