# Generated by Django 3.1 on 2023-08-11 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_delete_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
    ]
