# Generated by Django 4.2.4 on 2023-08-11 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20230811_0336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
