# Generated by Django 3.1 on 2023-08-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='place',
            new_name='City',
        ),
    ]
